@startuml Diagrama_de_Clases


class Administracion {

    -añadirProfesor()
    -darDeBajaProfesor()
    -modificarProfesor()
    -añadirGrupo()
    -eliminarGrupo()
    -modificarGrupo()

}

class Profesor {

    +UUID id
    +String nombre

    +añadirAlumno()
    +darDeBajaAlumno()
    +modificarAlumno()
    +registrarAsistencia()
    +expedirInformeMensual()

}

class Tarjeta {

    +NFC nfc

}

class Alumno {

    +UUID id
    +String nombre
    +Tarjeta tarjeta
    +Asistencia asistencias[]

}

class Grupo {

    +UUID id
    +Alumno alumnos[1..]

}

class Asistencia {

    +Date fecha
    +Alumno alumno
    +boolean asistencia

}

Grupo --* Alumno
Alumno "1"--o "1" Tarjeta
Profesor "1"-right->"*" Grupo
Administracion ..|> Profesor
Administracion ..|> Grupo
Profesor ..|> Alumno
Profesor ..|> Asistencia
Alumno -left-o Asistencia


@enduml