@startuml Diagrama de Estados

state c1 <<choice>>

[*] -> Inicializacion

Inicializacion -> Espera_De_Información : [El profesor elige la opción "Registrar Asistencia"] 


Espera_De_Información -> Validando_Información : [El profesor elige el grupo a registrar asistencia] 

Validando_Información -> Esperando_Tarjeta : [Información valida] 

Esperando_Tarjeta -> Validando_Tarjeta : [Los alumnos escanean su tarjeta en el la app FCA-SA] 

Validando_Tarjeta -> c1 

c1 -> Esperando_Tarjeta : [Información no valida (Rechazada)]

c1 -> Actualizando_Asistencias : [Información valida(Aprobada)] 

Actualizando_Asistencias -> Realizado : [La asistencia es tomada] 

Realizado -> [*] 

@enduml